_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.11
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
batch_size:
    value: 2
cache:
    value: true
channel_weights:
    value:
        - 1
        - 2
        - 1
        - 1
dataset_mode:
    value: ACDC
device:
    value: cuda:1
ed_es_only:
    value: ""
epochs:
    value: 500
l2_norm:
    value: 1e-07
log_dir:
    value: ../../de_logistics/ACDC_1UNetlinear_02-07-11-35-01/
log_file_path:
    value: ../../de_logistics/ACDC_1UNetlinear_02-07-11-35-01/training.log
lr:
    value: 0.0001
max_channel:
    value: 256
num_classes:
    value: 4
patience:
    value: 15
pretrained:
    value: false
pretrained_weights:
    value: ./Synapse_weights_1u1d
wandb:
    value: true
warmup_epochs:
    value: 10
